#        _                 _ _   _         
#   __ _| | __ _  ___ _ __(_) |_| |_ _   _ 
#  / _` | |/ _` |/ __| '__| | __| __| | | |
# | (_| | | (_| | (__| |  | | |_| |_| |_| |
#  \__,_|_|\__,_|\___|_|  |_|\__|\__|\__, |
#                                    |___/ 


[font]
normal = {family = "IBM Plex Mono"}
size = 12.0


[cursor]
style = {blinking = "On"}
blink_timeout = 0


[mouse]
hide_when_typing = true

