#        _                 _ _   _         
#   __ _| | __ _  ___ _ __(_) |_| |_ _   _ 
#  / _` | |/ _` |/ __| '__| | __| __| | | |
# | (_| | | (_| | (__| |  | | |_| |_| |_| |
#  \__,_|_|\__,_|\___|_|  |_|\__|\__|\__, |
#                                    |___/ 


[general]
import = [
    "~/.config/alacritty/colorschemes/one-dark.toml",
]


[env]
TERM = "xterm-256color"


[font]
normal = {family = "IBM Plex Mono"}
size = 13.0


[cursor]
style = {blinking = "On"}
blink_timeout = 0


[mouse]
hide_when_typing = true

